# Generated by Django 4.1.2 on 2022-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='', max_length=140),
        ),
    ]
