# Generated by Django 4.1.2 on 2022-12-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='category',
            field=models.CharField(default='', max_length=140),
        ),
    ]
