# Generated by Django 4.1.2 on 2022-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_entertainment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
