# Generated by Django 4.1.2 on 2022-12-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_entertainment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='name',
        ),
    ]
